class Color {

    constructor(col) { /* TODO document why this constructor is empty */ }

    public static get AliceBlue(): string { return "AliceBlue"; }
    public static get AntiqueWhite(): string { return "AntiqueWhite"; }
    public static get Aqua(): string { return "Aqua"; }
    public static get Aquamarine(): string { return "Aquamarine"; }
    public static get Azure(): string { return "Azure"; }
    public static get Beige(): string { return "Beige"; }
    public static get Bisque(): string { return "Bisque"; }
    public static get Black(): string { return "Black"; }
    public static get BlanchedAlmond(): string { return "BlanchedAlmond"; }
    public static get Blue(): string { return "Blue"; }
    public static get BlueViolet(): string { return "BlueViolet"; }
    public static get Brown(): string { return "Brown"; }
    public static get BurlyWood(): string { return "BurlyWood"; }
    public static get CadetBlue(): string { return "CadetBlue"; }
    public static get Chartreuse(): string { return "Chartreuse"; }
    public static get Chocolate(): string { return "Chocolate"; }
    public static get Coral(): string { return "Coral"; }
    public static get CornflowerBlue(): string { return "CornflowerBlue"; }
    public static get Cornsilk(): string { return "Cornsilk"; }
    public static get Crimson(): string { return "Crimson"; }
    public static get Cyan(): string { return "Cyan"; }
    public static get DarkBlue(): string { return "DarkBlue"; }
    public static get DarkCyan(): string { return "DarkCyan"; }
    public static get DarkGoldenrod(): string { return "DarkGoldenrod"; }
    public static get DarkGray(): string { return "DarkGray"; }
    public static get DarkGreen(): string { return "DarkGreen"; }
    public static get DarkKhaki(): string { return "DarkKhaki"; }
    public static get DarkMagenta(): string { return "DarkMagenta"; }
    public static get DarkOliveGreen(): string { return "DarkOliveGreen"; }
    public static get DarkOrange(): string { return "DarkOrange"; }
    public static get DarkOrchid(): string { return "DarkOrchid"; }
    public static get DarkRed(): string { return "DarkRed"; }
    public static get DarkSalmon(): string { return "DarkSalmon"; }
    public static get DarkSeaGreen(): string { return "DarkSeaGreen"; }
    public static get DarkSlateBlue(): string { return "DarkSlateBlue"; }
    public static get DarkSlateGray(): string { return "DarkSlateGray"; }
    public static get DarkTurquoise(): string { return "DarkTurquoise"; }
    public static get DarkViolet(): string { return "DarkViolet"; }
    public static get DeepPink(): string { return "DeepPink"; }
    public static get DeepSkyBlue(): string { return "DeepSkyBlue"; }
    public static get DimGray(): string { return "DimGray"; }
    public static get DodgerBlue(): string { return "DodgerBlue"; }
    public static get Firebrick(): string { return "Firebrick"; }
    public static get FloralWhite(): string { return "FloralWhite"; }
    public static get ForestGreen(): string { return "ForestGreen"; }
    public static get Fuchsia(): string { return "Fuchsia"; }
    public static get Gainsboro(): string { return "Gainsboro"; }
    public static get GhostWhite(): string { return "GhostWhite"; }
    public static get Gold(): string { return "Gold"; }
    public static get Goldenrod(): string { return "Goldenrod"; }
    public static get Gray(): string { return "Gray"; }
    public static get Green(): string { return "Green"; }
    public static get GreenYellow(): string { return "GreenYellow"; }
    public static get Honeydew(): string { return "Honeydew"; }
    public static get HotPink(): string { return "HotPink"; }
    public static get IndianRed(): string { return "IndianRed"; }
    public static get Indigo(): string { return "Indigo"; }
    public static get Ivory(): string { return "Ivory"; }
    public static get Khaki(): string { return "Khaki"; }
    public static get Lavender(): string { return "Lavender"; }
    public static get LavenderBlush(): string { return "LavenderBlush"; }
    public static get LawnGreen(): string { return "LawnGreen"; }
    public static get LemonChiffon(): string { return "LemonChiffon"; }
    public static get LightBlue(): string { return "LightBlue"; }
    public static get LightCoral(): string { return "LightCoral"; }
    public static get LightCyan(): string { return "LightCyan"; }
    public static get LightGoldenrodYellow(): string { return "LightGoldenrodYellow"; }
    public static get LightGreen(): string { return "LightGreen"; }
    public static get LightGray(): string { return "LightGray"; }
    public static get LightPink(): string { return "LightPink"; }
    public static get LightSalmon(): string { return "LightSalmon"; }
    public static get LightSeaGreen(): string { return "LightSeaGreen"; }
    public static get LightSkyBlue(): string { return "LightSkyBlue"; }
    public static get LightSlateGray(): string { return "LightSlateGray"; }
    public static get LightSteelBlue(): string { return "LightSteelBlue"; }
    public static get LightYellow(): string { return "LightYellow"; }
    public static get Lime(): string { return "Lime"; }
    public static get LimeGreen(): string { return "LimeGreen"; }
    public static get Linen(): string { return "Linen"; }
    public static get Magenta(): string { return "Magenta"; }
    public static get Maroon(): string { return "Maroon"; }
    public static get MediumAquamarine(): string { return "MediumAquamarine"; }
    public static get MediumBlue(): string { return "MediumBlue"; }
    public static get MediumOrchid(): string { return "MediumOrchid"; }
    public static get MediumPurple(): string { return "MediumPurple"; }
    public static get MediumSeaGreen(): string { return "MediumSeaGreen"; }
    public static get MediumSlateBlue(): string { return "MediumSlateBlue"; }
    public static get MediumSpringGreen(): string { return "MediumSpringGreen"; }
    public static get MediumTurquoise(): string { return "MediumTurquoise"; }
    public static get MediumVioletRed(): string { return "MediumVioletRed"; }
    public static get MidnightBlue(): string { return "MidnightBlue"; }
    public static get MintCream(): string { return "MintCream"; }
    public static get MistyRose(): string { return "MistyRose"; }
    public static get Moccasin(): string { return "Moccasin"; }
    public static get NavajoWhite(): string { return "NavajoWhite"; }
    public static get Navy(): string { return "Navy"; }
    public static get OldLace(): string { return "OldLace"; }
    public static get Olive(): string { return "Olive"; }
    public static get OliveDrab(): string { return "OliveDrab"; }
    public static get Orange(): string { return "Orange"; }
    public static get OrangeRed(): string { return "OrangeRed"; }
    public static get Orchid(): string { return "Orchid"; }
    public static get PaleGoldenrod(): string { return "PaleGoldenrod"; }
    public static get PaleGreen(): string { return "PaleGreen"; }
    public static get PaleTurquoise(): string { return "PaleTurquoise"; }
    public static get PaleVioletRed(): string { return "PaleVioletRed"; }
    public static get PapayaWhip(): string { return "PapayaWhip"; }
    public static get PeachPuff(): string { return "PeachPuff"; }
    public static get Peru(): string { return "Peru"; }
    public static get Pink(): string { return "Pink"; }
    public static get Plum(): string { return "Plum"; }
    public static get PowderBlue(): string { return "PowderBlue"; }
    public static get Purple(): string { return "Purple"; }
    public static get Red(): string { return "Red"; }
    public static get RosyBrown(): string { return "RosyBrown"; }
    public static get RoyalBlue(): string { return "RoyalBlue"; }
    public static get SaddleBrown(): string { return "SaddleBrown"; }
    public static get Salmon(): string { return "Salmon"; }
    public static get SandyBrown(): string { return "SandyBrown"; }
    public static get SeaGreen(): string { return "SeaGreen"; }
    public static get SeaShell(): string { return "SeaShell"; }
    public static get Sienna(): string { return "Sienna"; }
    public static get Silver(): string { return "Silver"; }
    public static get SkyBlue(): string { return "SkyBlue"; }
    public static get SlateBlue(): string { return "SlateBlue"; }
    public static get SlateGray(): string { return "SlateGray"; }
    public static get Snow(): string { return "Snow"; }
    public static get SpringGreen(): string { return "SpringGreen"; }
    public static get SteelBlue(): string { return "SteelBlue"; }
    public static get Tan(): string { return "Tan"; }
    public static get Teal(): string { return "Teal"; }
    public static get Thistle(): string { return "Thistle"; }
    public static get Tomato(): string { return "Tomato"; }
    public static get Turquoise(): string { return "Turquoise"; }
    public static get Violet(): string { return "Violet"; }
    public static get Wheat(): string { return "Wheat"; }
    public static get White(): string { return "White"; }
    public static get WhiteSmoke(): string { return "WhiteSmoke"; }
    public static get Yellow(): string { return "Yellow"; }
    public static get YellowGreen(): string { return "YellowGreen"; }

}